//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE_TABLE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string STATUS { get; set; }
        public int ID_EMP { get; set; }
    }
}
