//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_AMS
    {
        public int ID_EMP { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string CONTACT { get; set; }
        public string BIKE { get; set; }
        public string PASSWORK { get; set; }
    
        public virtual EMP_AMS EMP_AMS1 { get; set; }
        public virtual EMP_AMS EMP_AMS2 { get; set; }
    }
}
